ALTER TABLE locations DROP COLUMN id;
ALTER TABLE locations ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL;
ALTER TABLE locations ADD CONSTRAINT locations_pk PRIMARY KEY (id);

SELECT SETVAL('locations_id_seq', COALESCE(MAX(id), 1) ) FROM locations;

ALTER TABLE locations ALTER COLUMN lattitude TYPE varchar(25);
ALTER TABLE locations ALTER COLUMN longtitude TYPE varchar(25);
