CREATE TABLE wishlists
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                     BIGINT,
    product_id                  BIGINT,
    CONSTRAINT wishlists_pk     PRIMARY KEY (id),
    FOREIGN KEY(user_id)
        REFERENCES users(id),
    FOREIGN KEY(product_id)
        REFERENCES products(id)
);

INSERT INTO "wishlists" (user_id,product_id) VALUES
(1,3),
(1,4),
(2,1),
(2,2),
(2,7);

SELECT SETVAL('public.wishlists_id_seq', COALESCE(MAX(id), 1) ) FROM public.wishlists;